### ISSUE TITLE
اتصال برای جوا اسکریپت

### ISSUE THREAD

**Issue by ashkankiani** [Leakfarsi/Leakfa.com#1]
برای جاوا اسکریپت api به چه صورت باید درخواست بدهد تا ریسپانس رو دریافت کنیم؟

**Comment by Leakfarsi** [comment]
میتونید اطلاعات بیشتر در مورد نحوه استفاده از API رو در [اینجا](https://github.com/Leakfarsi/Leakfa.com/tree/api-documents) پیدا کنید. البته فعلا برای جاوا چیزی تعریف نشده.
