### ISSUE TITLE
شماره من هک شده

### ISSUE THREAD

**Issue by Negar-Amiri** [Leakfarsi/Leakfa.com#2]
شماره من توی لیست بانک ملت بوده و هک شده.
یعنی الان همه به اطلاعات من مثل آدرس و کد ملی دسترسی دارن؟

وبسایت هایی مثل "HIBP" و وبسایت شما این اطلاعات رو دارن که میتونن چک کنن این مسئله رو دیگه یعنی الان شما خودتون این اطلاعات رو دارید الان شما آدرس من رو میدونید؟

و این به اصطلاح breache ها رو از کجا میشه پیدا کرد یا دانلود کرد که بفهمیم دقیقا چه اطلاعاتی از ما توش هست؟

**Comment by Leakfarsi** [comment]
اطلاعات مورد نیاز جهت استعلام کاربران از بانک‌های اطلاعاتی افشاشده استخراج و بعد از تبدیل به هش SHA-1 به سامانه جستجوی نشت اضافه می‌شوند. داده‌های اصلی، برای جلوگیری از نشت ثانویه حذف می‌شوند. اطلاعات بیشتر رو میتونید در [درباره ما](https://leakfa.com/about) و [خط مشی](https://leakfa.com/policy) بخونید.
